HEAD:
    #keypoint: keypoint, R,G,B for line color
    nose: "left_ear,102, 204, 255"
    left_ear: "right_ear, 102, 0, 204"
    right_ear: "nose, 51, 102, 255"
BODY:
    tail_base: "left_hip,255, 128, 0"
    right_hip: "tail_base,153, 255, 204"
    neck: "right_hip,255, 195, 77"
    left_hip: "neck,153, 255, 204"

NAME:
    resident
    mouse
    intruder
    vole

EVENTS:
    huddling
    grooming 
    rearing
    sniffing
    investigation
    LeftInteract
    RightInteract
    nose_to_nose
    fighting
    flank_sniffing
    chasing
    anogenital_sniffing
    walking
    attack
    pounce
    chase
    running
    running_away
    exploring
    immobility
    autogrooming
    nose_to_nose_sniffing
    intruder_rearing
